version: '3.7'

services:
  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./services/api:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - NODE_ENV=development
      - HOST=0.0.0.0
      - DB_URL=mongo:27017
      - DB_NAME=xacoaching-dev
      - WAIT_HOSTS=mongo:27017

volumes:
  data:
