version: '3.7'

services:
  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    volumes:
      - ./services/users:/usr/src/app
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - HOST=0.0.0.0
      - DB_URL=mongo:27017
      - DB_NAME=xacoaching-dev

  mongo:
    image: mongo
    volumes:
      - data:/data/db
    ports:
      - 27017:27017

volumes:
  data:
