"""empty message

Revision ID: e17ae1a4ee41
Revises: cf46df8049a4
Create Date: 2019-06-08 11:09:22.530407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e17ae1a4ee41'
down_revision = 'cf46df8049a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'coach', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coach', type_='unique')
    # ### end Alembic commands ###
